let matrixData=[],allotmentData=[];
const DATASETS={
  AIQ:{label:"All India Quota",rounds:{1:{matrix:"data/aiq_seat_matrix_r1_2025.csv",allotments:null}}},
  BIHAR:{label:"Bihar PGMAC",rounds:{1:{matrix:null,allotments:"data/pgmac_allotment_r1_2025.csv"}}}
};
const n=v=>Number(String(v??"").replace(/,/g,""))||0;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const clean=v=>String(v??"").trim().toLowerCase();
function parseCSV(t){const rows=[];let row=[],cell="",q=false;for(let i=0;i<t.length;i++){let c=t[i],nx=t[i+1];if(c==='"'){if(q&&nx==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&nx==='\n')i++;row.push(cell);cell="";if(row.some(v=>v!==""))rows.push(row);row=[]}else cell+=c}if(cell!==""||row.length){row.push(cell);if(row.some(v=>v!==""))rows.push(row)}const h=(rows.shift()||[]).map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((x,i)=>[x,(r[i]??"").trim()])))}
async function fetchCSV(path){if(!path)return[];const r=await fetch(path);if(!r.ok)throw Error(path);return parseCSV(await r.text())}
function currentConfig(){const key=document.getElementById("globalCounselling").value,round=document.getElementById("globalRound").value;return {key,round,cfg:DATASETS[key],data:DATASETS[key].rounds[round]}}
function populateRounds(){const key=document.getElementById("globalCounselling").value,cfg=DATASETS[key];const sel=document.getElementById("globalRound");const rounds=Object.keys(cfg.rounds).sort((a,b)=>Number(a)-Number(b));sel.innerHTML=rounds.map(r=>`<option value="${r}">Round ${r}</option>`).join("");}
async function applySelection(){const {key,round,cfg,data}=currentConfig();try{[matrixData,allotmentData]=await Promise.all([fetchCSV(data.matrix),fetchCSV(data.allotments)]);const label=`${cfg.label} · 2025 · Round ${round}`;document.getElementById("status").textContent=`${label} loaded`;document.getElementById("selectionNote").innerHTML=`<span class="ok">●</span> <b>${cfg.label}</b> · 2025 · <b>Round ${round}</b> selected. Search below to explore.`;document.getElementById("matrixExplorer").hidden=!data.matrix;document.getElementById("matrixPrompt").hidden=!!data.matrix;document.getElementById("allotmentExplorer").hidden=!data.allotments;document.getElementById("allotmentPrompt").hidden=!!data.allotments;document.querySelector(".section-title h2").innerHTML=`Round ${esc(round)} <span>·</span> 2025`;updateStats();populateFilters();clearFilters();renderMatrix(true);renderAllotments(true);renderInsights();resetRankStrategy();}
catch(e){console.error(e);document.getElementById("status").textContent="Data could not be loaded";document.getElementById("selectionNote").innerHTML='<span style="color:#d14343">●</span> Could not load this dataset. Check that the CSV file exists in the data folder.';resetRankStrategy();}}
function updateStats(){document.getElementById("totalSeats").textContent=matrixData.length?matrixData.reduce((s,r)=>s+n(r.total_seats),0).toLocaleString("en-IN"):"—";document.getElementById("aiqInstitutes").textContent=matrixData.length?new Set(matrixData.map(r=>r.institute)).size.toLocaleString("en-IN"):"—";document.getElementById("aiqPrograms").textContent=matrixData.length?new Set(matrixData.map(r=>r.program)).size.toLocaleString("en-IN"):"—";document.getElementById("allotmentCount").textContent=allotmentData.length?allotmentData.length.toLocaleString("en-IN"):"—"}
function populateFilters(){document.getElementById("matrixQuota").innerHTML='<option value="">All quotas</option>'+[...new Set(matrixData.map(r=>r.quota).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join("");document.getElementById("allotCategory").innerHTML='<option value="">All categories</option>'+[...new Set(allotmentData.map(r=>r.allotted_category).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join("");document.getElementById("rankCategory").innerHTML='<option value="">All candidate categories</option>'+[...new Set(allotmentData.map(r=>r.neet_cat).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join("")}
function clearFilters(){["matrixInstitute","matrixProgram","allotInstitute","allotBranch","allotAir","myRank","rankBranch","rankInstitute"].forEach(id=>{const el=document.getElementById(id);if(el)el.value=""});["matrixQuota","allotCategory","rankCategory"].forEach(id=>{const el=document.getElementById(id);if(el)el.value=""})}
function renderMatrix(initial=false){if(!matrixData.length)return;const i=clean(document.getElementById("matrixInstitute").value),p=clean(document.getElementById("matrixProgram").value),q=document.getElementById("matrixQuota").value;if(initial||(!i&&!p&&!q)){document.getElementById("matrixBody").innerHTML='<tr><td colspan="9" style="text-align:center;padding:25px;color:#7b8798">Enter a college, specialty or quota to view matching seats.</td></tr>';return}const rows=matrixData.filter(r=>(!i||clean(r.institute).includes(i))&&(!p||clean(r.program).includes(p))&&(!q||r.quota===q)).slice(0,250);document.getElementById("matrixBody").innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.institute)}</td><td>${esc(r.program)}</td><td>${esc(r.quota)}</td><td>${n(r.open)}</td><td>${n(r.gen_ews)}</td><td>${n(r.obc)}</td><td>${n(r.sc)}</td><td>${n(r.st)}</td><td><b>${n(r.total_seats)}</b></td></tr>`).join(""):'<tr><td colspan="9" style="text-align:center;padding:25px;color:#7b8798">No matching records.</td></tr>'}
function renderAllotments(initial=false){if(!allotmentData.length)return;const i=clean(document.getElementById("allotInstitute").value),b=clean(document.getElementById("allotBranch").value),c=document.getElementById("allotCategory").value,m=n(document.getElementById("allotAir").value);if(initial||(!i&&!b&&!c&&!m)){document.getElementById("allotmentBody").innerHTML='<tr><td colspan="7" style="text-align:center;padding:25px;color:#7b8798">Enter a college, specialty, category or AIR to view results.</td></tr>';return}const rows=allotmentData.filter(r=>(!i||clean(r.institute).includes(i))&&(!b||clean(r.branch).includes(b))&&(!c||r.allotted_category===c)&&(!m||n(r.neet_air)<=m)).sort((a,b)=>n(a.neet_air)-n(b.neet_air)).slice(0,250);document.getElementById("allotmentBody").innerHTML=rows.length?rows.map(r=>`<tr><td><b>${esc(r.neet_air)}</b></td><td>${esc(r.institute)}</td><td>${esc(r.branch)}</td><td>${esc(r.neet_cat||r.category)}</td><td>${esc(r.allotted_category)}</td><td>${esc(r.seat_type)}</td><td>${esc(r.remarks)}</td></tr>`).join(""):'<tr><td colspan="7" style="text-align:center;padding:25px;color:#7b8798">No matching records.</td></tr>'}
function resetRankStrategy(){const has=allotmentData.length>0;document.getElementById("rankSource").textContent=has?`${allotmentData.length.toLocaleString("en-IN")} allotments loaded`:"Allotment history not loaded for this dataset";document.getElementById("rankEmpty").hidden=false;document.getElementById("rankResults").hidden=true;document.getElementById("rankSummary").innerHTML="";document.getElementById("rankResultList").innerHTML=""}
function rankLabel(row,rank){const gap=row.maxAir-rank;if(gap>=0)return {cls:"reachable",label:"Historically reachable",gap};return {cls:"outside",label:"Outside observed range",gap}}
function runRankStrategy(){const rank=n(document.getElementById("myRank").value),branch=clean(document.getElementById("rankBranch").value),inst=clean(document.getElementById("rankInstitute").value),cat=document.getElementById("rankCategory").value;if(!rank||rank<1){document.getElementById("rankEmpty").hidden=false;document.getElementById("rankResults").hidden=true;return}if(!allotmentData.length){document.getElementById("rankEmpty").hidden=false;document.getElementById("rankEmpty").innerHTML='<div>!</div><b>No allotment history is loaded for this counselling</b><span>Add the round-wise allotment result to unlock My Rank.</span>';return}let rows=allotmentData.filter(r=>n(r.neet_air)>0&&(!branch||clean(r.branch).includes(branch))&&(!inst||clean(r.institute).includes(inst))&&(!cat||r.neet_cat===cat));const groups=new Map();rows.forEach(r=>{const key=`${r.institute}|||${r.branch}`;if(!groups.has(key))groups.set(key,{institute:r.institute,branch:r.branch,airs:[],count:0,categories:new Set()});const g=groups.get(key);g.airs.push(n(r.neet_air));g.count++;if(r.neet_cat)g.categories.add(r.neet_cat)});let result=[...groups.values()].map(g=>{g.minAir=Math.min(...g.airs);g.maxAir=Math.max(...g.airs);g.rankCount=g.airs.length;const gap=g.maxAir-rank;return {...g,gap,reachable:gap>=0}}).filter(g=>g.reachable).sort((a,b)=>b.gap-a.gap||a.maxAir-b.maxAir).slice(0,20);const totalReachable=[...groups.values()].filter(g=>g.maxAir>=rank).length;const rankSummary=document.getElementById("rankSummary");rankSummary.innerHTML=`<div><strong>${totalReachable}</strong><span>matching college + branch groups were historically reachable at AIR ${rank.toLocaleString("en-IN")}</span></div><small>${branch||inst||cat?"Filters applied · ":""}Showing up to 20 with the largest historical rank buffer.</small>`;document.getElementById("rankResultList").innerHTML=result.length?result.map((r,idx)=>{const l=rankLabel(r,rank);return `<article class="rank-result"><div class="rank-rank">${String(idx+1).padStart(2,"0")}</div><div class="rank-main"><strong>${esc(r.branch)}</strong><span>${esc(r.institute)}</span><div class="rank-tags"><em class="${l.cls}">${l.label}</em><em>${r.rankCount} observed allotment${r.rankCount===1?"":"s"}</em></div></div><div class="rank-metrics"><div><small>Your AIR</small><b>${rank.toLocaleString("en-IN")}</b></div><div><small>Observed last AIR</small><b>${r.maxAir.toLocaleString("en-IN")}</b></div><div class="buffer"><small>Buffer</small><b>+${r.gap.toLocaleString("en-IN")}</b></div></div></article>`}).join(""):'<div class="rank-empty"><div>—</div><b>No historically reachable match found</b><span>Try removing a filter or check a different counselling/round.</span></div>';document.getElementById("rankEmpty").hidden=true;document.getElementById("rankResults").hidden=false}
function renderInsights(){const p={},i={};matrixData.forEach(r=>{p[r.program]=(p[r.program]||0)+n(r.total_seats);i[r.institute]=(i[r.institute]||0)+n(r.total_seats)});const tp=Object.entries(p).sort((a,b)=>b[1]-a[1])[0],ti=Object.entries(i).sort((a,b)=>b[1]-a[1])[0],air=allotmentData.filter(r=>n(r.neet_air)>0).sort((a,b)=>n(a.neet_air)-n(b.neet_air))[0];document.getElementById("topProgram").textContent=tp?`${tp[0]} — ${tp[1].toLocaleString("en-IN")} seats`:"—";document.getElementById("topInstitute").textContent=ti?`${ti[0]} — ${ti[1].toLocaleString("en-IN")} seats`:"—";document.getElementById("bestObserved").textContent=air?`AIR ${n(air.neet_air).toLocaleString("en-IN")}`:"—"}

document.getElementById("globalCounselling").addEventListener("change",()=>{populateRounds();applySelection()});
document.getElementById("globalRound").addEventListener("change",applySelection);
document.getElementById("applySelection").addEventListener("click",applySelection);
document.getElementById("matrixSearch").addEventListener("click",()=>renderMatrix());
document.getElementById("allotSearch").addEventListener("click",()=>renderAllotments());
document.getElementById("rankSearch").addEventListener("click",runRankStrategy);
document.querySelectorAll(".quick button").forEach(b=>b.addEventListener("click",()=>{document.getElementById("matrixProgram").value=b.dataset.q;renderMatrix()}));
["matrixInstitute","matrixProgram"].forEach(id=>document.getElementById(id).addEventListener("keydown",e=>{if(e.key==="Enter")renderMatrix()}));
["allotInstitute","allotBranch","allotAir"].forEach(id=>document.getElementById(id).addEventListener("keydown",e=>{if(e.key==="Enter")renderAllotments()}));
["myRank","rankBranch","rankInstitute"].forEach(id=>document.getElementById(id).addEventListener("keydown",e=>{if(e.key==="Enter")runRankStrategy()}));
populateRounds();applySelection();
