let matrixData=[],allotmentData=[];
const DATASETS={AIQ:{label:"All India Quota (AIQ)",matrix:"data/aiq_seat_matrix_r1_2025.csv",allotments:null},BIHAR:{label:"Bihar PGMAC",matrix:null,allotments:"data/pgmac_allotment_r1_2025.csv"}};
const n=v=>Number(String(v||"").replace(/,/g,""))||0;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function parseCSV(t){const rows=[];let row=[],cell="",q=false;for(let i=0;i<t.length;i++){let c=t[i],nx=t[i+1];if(c==='"'){if(q&&nx==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&nx==='\n')i++;row.push(cell);cell="";if(row.some(v=>v!==""))rows.push(row);row=[]}else cell+=c}if(cell!==""||row.length){row.push(cell);if(row.some(v=>v!==""))rows.push(row)}const h=(rows.shift()||[]).map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((x,i)=>[x,(r[i]??"").trim()])))} 
async function fetchCSV(path){if(!path)return[];const r=await fetch(path);if(!r.ok)throw Error(path);return parseCSV(await r.text())}
async function applySelection(){
 const key=document.getElementById("globalCounselling").value,cfg=DATASETS[key];
 try{[matrixData,allotmentData]=await Promise.all([fetchCSV(cfg.matrix),fetchCSV(cfg.allotments)]);
 document.getElementById("status").textContent=`${cfg.label} · 2025 · Round 1 loaded`;
 document.getElementById("selectionNote").innerHTML=`<b>${cfg.label}</b> · 2025 · <b>Round 1</b> selected. Now search the explorer below.`;
 document.getElementById("matrixExplorer").hidden=!cfg.matrix;document.getElementById("matrixPrompt").hidden=!!cfg.matrix;
 document.getElementById("allotmentExplorer").hidden=!cfg.allotments;document.getElementById("allotmentPrompt").hidden=!!cfg.allotments;
 updateStats();populateFilters();clearFilters();renderMatrix(true);renderAllotments(true);renderInsights();
 }catch(e){console.error(e);document.getElementById("status").textContent="Data could not be loaded"}
}
function updateStats(){document.getElementById("totalSeats").textContent=matrixData.reduce((s,r)=>s+n(r.total_seats),0).toLocaleString("en-IN")||"—";document.getElementById("aiqInstitutes").textContent=matrixData.length?new Set(matrixData.map(r=>r.institute)).size:"—";document.getElementById("aiqPrograms").textContent=matrixData.length?new Set(matrixData.map(r=>r.program)).size:"—";document.getElementById("allotmentCount").textContent=allotmentData.length?allotmentData.length.toLocaleString("en-IN"):"—"}
function populateFilters(){document.getElementById("matrixQuota").innerHTML='<option value="">All quotas</option>'+[...new Set(matrixData.map(r=>r.quota).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join("");document.getElementById("allotCategory").innerHTML='<option value="">All categories</option>'+[...new Set(allotmentData.map(r=>r.allotted_category).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join("")}
function clearFilters(){["matrixInstitute","matrixProgram","allotInstitute","allotBranch","allotAir"].forEach(id=>document.getElementById(id).value="");document.getElementById("matrixQuota").value="";document.getElementById("allotCategory").value=""}
function renderMatrix(initial=false){if(!matrixData.length)return;if(initial||!document.getElementById("matrixInstitute").value.trim()&&!document.getElementById("matrixProgram").value.trim()&&!document.getElementById("matrixQuota").value){document.getElementById("matrixBody").innerHTML='<tr><td colspan="9" class="empty">Search by institute, specialty or quota to see results.</td></tr>';return}const i=document.getElementById("matrixInstitute").value.toLowerCase(),p=document.getElementById("matrixProgram").value.toLowerCase(),q=document.getElementById("matrixQuota").value;const rows=matrixData.filter(r=>(!i||r.institute.toLowerCase().includes(i))&&(!p||r.program.toLowerCase().includes(p))&&(!q||r.quota===q)).slice(0,250);document.getElementById("matrixBody").innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.institute)}</td><td>${esc(r.program)}</td><td>${esc(r.quota)}</td><td>${n(r.open)}</td><td>${n(r.gen_ews)}</td><td>${n(r.obc)}</td><td>${n(r.sc)}</td><td>${n(r.st)}</td><td><b>${n(r.total_seats)}</b></td></tr>`).join(""):'<tr><td colspan="9" class="empty">No matching records.</td></tr>'}
function renderAllotments(initial=false){if(!allotmentData.length)return;if(initial||!document.getElementById("allotInstitute").value.trim()&&!document.getElementById("allotBranch").value.trim()&&!document.getElementById("allotCategory").value&&!document.getElementById("allotAir").value){document.getElementById("allotmentBody").innerHTML='<tr><td colspan="7" class="empty">Search by institute, specialty, category or AIR to see results.</td></tr>';return}const i=document.getElementById("allotInstitute").value.toLowerCase(),b=document.getElementById("allotBranch").value.toLowerCase(),c=document.getElementById("allotCategory").value,m=n(document.getElementById("allotAir").value);const rows=allotmentData.filter(r=>(!i||r.institute.toLowerCase().includes(i))&&(!b||r.branch.toLowerCase().includes(b))&&(!c||r.allotted_category===c)&&(!m||n(r.neet_air)<=m)).sort((a,b)=>n(a.neet_air)-n(b.neet_air)).slice(0,250);document.getElementById("allotmentBody").innerHTML=rows.length?rows.map(r=>`<tr><td><b>${esc(r.neet_air)}</b></td><td>${esc(r.institute)}</td><td>${esc(r.branch)}</td><td>${esc(r.neet_cat||r.category)}</td><td>${esc(r.allotted_category)}</td><td>${esc(r.seat_type)}</td><td>${esc(r.remarks)}</td></tr>`).join(""):'<tr><td colspan="7" class="empty">No matching records.</td></tr>'}
function renderInsights(){const p={},i={};matrixData.forEach(r=>{p[r.program]=(p[r.program]||0)+n(r.total_seats);i[r.institute]=(i[r.institute]||0)+n(r.total_seats)});const tp=Object.entries(p).sort((a,b)=>b[1]-a[1])[0],ti=Object.entries(i).sort((a,b)=>b[1]-a[1])[0],air=allotmentData.filter(r=>n(r.neet_air)>0).sort((a,b)=>n(a.neet_air)-n(b.neet_air))[0];document.getElementById("topProgram").textContent=tp?`${tp[0]} — ${tp[1].toLocaleString("en-IN")} seats`:"—";document.getElementById("topInstitute").textContent=ti?`${ti[0]} — ${ti[1].toLocaleString("en-IN")} seats`:"—";document.getElementById("bestObserved").textContent=air?`AIR ${n(air.neet_air).toLocaleString("en-IN")}`:"—"}
document.getElementById("applySelection").addEventListener("click",applySelection);document.getElementById("matrixSearch").addEventListener("click",()=>renderMatrix());document.getElementById("allotSearch").addEventListener("click",()=>renderAllotments());
["matrixInstitute","matrixProgram"].forEach(id=>document.getElementById(id).addEventListener("keydown",e=>{if(e.key==="Enter")renderMatrix()}));["allotInstitute","allotBranch","allotAir"].forEach(id=>document.getElementById(id).addEventListener("keydown",e=>{if(e.key==="Enter")renderAllotments()}));applySelection();
